name: bitchat
description: "A secure, decentralized, peer-to-peer messaging app that works over Bluetooth mesh networks. No internet required, no servers, no phone numbers - just pure encrypted communication."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # Required dependencies from tech standards
  flutter_reactive_ble: ^5.4.0      # BLE operations - do not upgrade without compatibility testing
  cryptography: ^2.7.0            # Encryption (X25519, AES-256-GCM, Ed25519)
  hive: ^2.2.3                    # Local storage and message persistence
  provider: ^6.1.1                # State management pattern
  permission_handler: ^12.0.1     # Platform permissions for Bluetooth/location

  # Additional core dependencies
  cupertino_icons: ^1.0.8
  pubspec_checker: ^1.1.0
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
 